### PR TITLE
.coafile: Add YAMLLintBear

### LINKED ISSUE #38: Check repository for .yml files using YAMLLintBear
Add YAMLLintBear in .coafile and fix .yml file issues raised by coala. See https://github.com/coala/coala-bears/pull/1799 for reference.
difficulty/newcomer

Opened via [gitter](https://gitter.im/coala/coala/?at=5945cc7ed83c50560c1b3403) by @Monal5031

### PR DESCRIPTION
**Pull request by soumya-ranjan7**
Added YAMLLintBear for fixing issues with .yml files

Closes #38

### CODE REVIEW

**Comment by soumya-ranjan7** [comment]
Hey @khanchi97. Actually I am new to git and I am still learning. I tried to squash the commands but I messed it up. Please review this new PR.

**Comment by prnvdixit** [comment]
@soumya-ranjan7 You should try not to push changes from your master branch - Try to make a separate branch for each patch :smile: 
Also, in case you are not able to solve any issue even after quite some research - Try to ask it on gitter channel always - someone would be around to help you 😄. eg. Now this issue has three PRs too (2 closed) (fortunately, all are opened by you 😃) - due to this, the reviews are apart in different PRs. Please, try to ask your doubts on gitter 😉.

**Comment by soumya-ranjan7** [comment]
@prnvdixit I am really sorry for creating 3 PRs for just a single issue. I actually asked a lot of things today on the gitter channel and did not want to annoy people by asking more.

**Comment by prnvdixit** [comment]
@soumya-ranjan7 It's fine 👍 - We all start as newcomers 😃 ... Just ask after trying by yourselves 😉

**Comment by soumya-ranjan7** [comment]
Okay. Thanks for the advice @prnvdixit.
Btw can you review my PR if you are free?

**Comment by prnvdixit** [comment]
@soumya-ranjan7 Someone would review it soon definitely 👍 - Bit occupied now 😄

**Comment by khanchi97** [comment]
ack 21f4f566

**Comment by sils** [comment]
@rultor merge

**Pull request merged**
